### ISSUE TITLE
How to create categories in Gally?

### ISSUE THREAD

**Issue by shochdoerfer** [Elastic-Suite/gally#532]
For a small test project, I set up Gally without installing the fixtures, and now I am wondering how categories get created in Gally? I would have expected to see a POST method but I can only see GET, PUT, and PATCH methods. Can you give me some hints how this is supposed to work?

**Comment by botisSmile** [comment]
The categories are created/updated in database during the category indexation process, in other words, when you add category documents from the API. You will find [here](https://github.com/Elastic-Suite/gally/wiki/Managing-your-content-with-Gally#sync-your-catalog-data) the explanations to put in place your catalog data via API.

**Comment by shochdoerfer** [comment]
Thanks for the clarification, that's what I thought but was not sure if my assumptions are correct.
