### ISSUE TITLE
How to make searchable attributes of a custom entity visible in Gally Admin?

### ISSUE THREAD

**Issue by shochdoerfer** [Elastic-Suite/gally#533]
To experiment a bit with Gally, I decided to see if I could use it to power the search on our static page company blog. For that reason, I created a new entity called "blogpost" and assigned 3 searchable attributes (ID, title, content). Since I configured the title and content attributes searchable, I was hoping to see the attributes listed in Gally Admin. But it looks like Gally Admin does only show the attributes defined by the product entity.

Is this by intention or a limitation by the current implementation?

**Comment by botisSmile** [comment]
For the moment, only product attributes are displayed in Gally Admin, but it's planned in the roadmap to add an entity selector on some screens.

**Comment by shochdoerfer** [comment]
Thx for the clarification. Looking forward to this feature!
