### ISSUE TITLE
What is needed to expose a custom entity?

### ISSUE THREAD

**Issue by shochdoerfer** [Elastic-Suite/gally#534]
This complements my question in #533: I want to expose my custom entity "blogpost" via GraphQL but I am struggling a bit to figure out what is needed. I created an entity and annotated it with the same `ApiResource` annotation you have used for the product entity. Additionally, I implemented a `BlogpostRequestTypeEnumType` similar to the `ProductRequestTypeEnumType` in Gally.

Now, when opening the GraphQL web UI, I get an error that the call to `$this->configurationProvider->getAvailableRequestType('blogpost')` fails because blogpost is not an array key.

Could you outline which steps need to be taken to implement a custom entity? I was hoping that this could be done purely by configuring things via Gally Admin or the Gally API. But is seems a bit of code/logic is also needed.

**Comment by botisSmile** [comment]
All the steps to manage a "custom entity" are described [here](https://github.com/Elastic-Suite/gally/wiki/Managing-your-content-with-Gally#managing-additional-content), don't hesitate if you have any question.

**Comment by shochdoerfer** [comment]
My bad, I've seen the wiki but somehow I missed the link in the right sidebar. That document explains a lot.
