### ISSUE TITLE
Explain and compare errors with "Cannot query field description on type Product"

### ISSUE THREAD

**Issue by shochdoerfer** [Elastic-Suite/gally#594]
After a new install of Gally 1.3, I removed the demo/test fixtures by running the command `bin/console HauteLook:fixtures:load -e prod.` 

Afterward, I synced attributes and products from my Sylius shop and tried to run the "Explain and compare" feature in Gally Admin. This caused the error "Cannot query field description on type Product" to appear. After reinstalling Gally 1.3 with all fixtures, the "Explain and compare" feature is working fine.

The same error occurs after running `./bin/console gally:structure:clean -f`. The output of the command shows that description attributes have been deleted:
```
Delete sourceField /metadata/6 description
Delete sourceField /metadata/8 description
```

**Comment by PierreGauthier** [comment]
Thank for reporting, It has been fixed by https://github.com/Elastic-Suite/gally-standard/pull/87
